# Generated by Django 3.1.9 on 2021-08-10 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='tax_reg_system',
            field=models.PositiveIntegerField(choices=[(1, 'VAT'), (2, 'PAN'), (3, 'N/A')], default=3, help_text='by default=1'),
        ),
    ]
