# Generated by Django 3.1.9 on 2021-08-02 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
        ('log_app', '0003_auto_20210727_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logsaledetail',
            name='ref_purchase_detail',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='purchase.purchasedetail'),
        ),
    ]
