# Generated by Django 3.1.9 on 2021-08-10 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0004_auto_20210802_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logcustomer',
            name='tax_reg_system',
            field=models.PositiveIntegerField(choices=[(1, 'VAT'), (2, 'PAN'), (3, 'N/A')], default=3, help_text='default value is 1'),
        ),
        migrations.AlterField(
            model_name='logsupplier',
            name='tax_reg_system',
            field=models.PositiveIntegerField(choices=[(1, 'VAT'), (2, 'PAN'), (3, 'N/A')], default=3, help_text='by default=1'),
        ),
    ]
