# Generated by Django 3.1.9 on 2021-07-12 05:30

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import src.core_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date_ad', models.DateTimeField()),
                ('created_date_bs', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date_ad', models.DateTimeField()),
                ('created_date_bs', models.CharField(max_length=10)),
                ('name', models.CharField(help_text='Name of the country can have max upto 50 characters, unique=True', max_length=50, unique=True)),
                ('country_code', models.CharField(blank=True, help_text='country code max length 5', max_length=5, null=True)),
                ('phone_code', models.CharField(blank=True, help_text='country code max length 5', max_length=5, null=True)),
                ('currency_name', models.CharField(blank=True, help_text='country code max length 50', max_length=50, null=True)),
                ('currency_symbol', models.CharField(blank=True, help_text='country code max length 3', max_length=3, null=True)),
                ('currency_code', models.CharField(blank=True, help_text='country code max length 3', max_length=3, null=True)),
                ('flag_image', models.ImageField(blank=True, help_text='Image can be max of 2 MB size, blank=True', upload_to='country_flag/', validators=[src.core_app.models.validate_image])),
                ('active', models.BooleanField(default=True, help_text='By default= true')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TaxGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date_ad', models.DateTimeField()),
                ('created_date_bs', models.CharField(max_length=10)),
                ('name', models.CharField(help_text='Name can have max of 20 characaters and must be unique', max_length=20, unique=True)),
                ('rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Default=0.0', max_digits=5)),
                ('display_order', models.IntegerField(default=0, help_text='Display order for ordering, default=0')),
                ('active', models.BooleanField(default=True, help_text='By default active=True')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date_ad', models.DateTimeField()),
                ('created_date_bs', models.CharField(max_length=10)),
                ('name', models.CharField(help_text='Province name can be max. of 50 characters and unique=True', max_length=50, unique=True)),
                ('active', models.BooleanField(default=True, help_text='by default=True')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentMode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date_ad', models.DateTimeField()),
                ('created_date_bs', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=15, unique=True)),
                ('active', models.BooleanField(default=0)),
                ('remarks', models.CharField(blank=True, max_length=50)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrganizationSetup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date_ad', models.DateTimeField()),
                ('created_date_bs', models.CharField(max_length=10)),
                ('name', models.CharField(help_text='Organization name should be maximum of 100 characters', max_length=100, unique=True)),
                ('address', models.CharField(blank=True, help_text='Organization name should be maximum of 100 characters', max_length=100, unique=True)),
                ('phone_no_1', models.CharField(blank=True, help_text='Phone no should be maximum of 15 characters', max_length=15, unique=True)),
                ('phone_no_2', models.CharField(blank=True, help_text='Phone no should be maximum of 15 characters', max_length=15)),
                ('mobile_no', models.CharField(blank=True, help_text='Mobile no should be maximum of 15 characters', max_length=15, unique=True)),
                ('pan_no', models.CharField(blank=True, help_text='PAN no. should be maximum of 15 characters', max_length=15, unique=True)),
                ('owner_name', models.CharField(blank=True, help_text='Owner name should be maximum of 50 characters', max_length=50, unique=True)),
                ('email', models.CharField(blank=True, help_text='Email Id. should be maximum of 70 characters', max_length=70, unique=True)),
                ('website_url', models.CharField(blank=True, help_text='Website address should be maximum of 50 characters', max_length=50, unique=True)),
                ('logo', models.ImageField(blank=True, upload_to='organization/', validators=[src.core_app.models.validate_image])),
                ('favicon', models.ImageField(blank=True, upload_to='organization/', validators=[src.core_app.models.validate_image])),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core_app.country')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrganizationRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date_ad', models.DateTimeField()),
                ('created_date_bs', models.CharField(max_length=10)),
                ('customer_seq_type', models.PositiveIntegerField(choices=[(1, 'AD'), (2, 'BS'), (3, 'SEQUENTIAL')], default=2, help_text='where 1=AD,2=BS,3=SEQUENTIAL  and default=2')),
                ('fiscal_session_type', models.PositiveIntegerField(choices=[(1, 'AD'), (2, 'BS')], default=2, help_text='Where 1 = AD , 2 = BS and default=2')),
                ('calendar_system', models.PositiveIntegerField(choices=[(1, 'AD'), (2, 'BS')], default=2, help_text='Where 1 = AD , 2 = BS and default=2')),
                ('enable_print', models.BooleanField(default=True)),
                ('print_preview', models.BooleanField(default=True)),
                ('billing_time_restriction', models.BooleanField(default=False)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('first_day_of_week', models.PositiveIntegerField(choices=[(1, 'SUNDAY'), (2, 'MONDAY'), (3, 'TUESDAY'), (4, 'WEDNESDAY'), (5, 'THURSDAY'), (6, 'FRIDAY'), (7, 'SATURDAY')], default=1, help_text='where 1 = Sunday ---- 7 =Saturday')),
                ('tax_system', models.PositiveIntegerField(choices=[(1, 'VAT'), (2, 'PAN')], default=1, help_text='where 1=VAT, 2=PAN')),
                ('round_off_limit', models.PositiveIntegerField(default=2)),
                ('item_expiry_date_sale_threshold', models.PositiveIntegerField(default=30)),
                ('tax_applicable', models.BooleanField(default=True)),
                ('tax_rate', models.FloatField(default=0.0, help_text='Tax rate', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date_ad', models.DateTimeField()),
                ('created_date_bs', models.CharField(max_length=10)),
                ('name', models.CharField(help_text='District name can be max. of 50 characters and unique=True', max_length=50, unique=True)),
                ('active', models.BooleanField(default=True, help_text='by default=True')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core_app.province')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DiscountScheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date_ad', models.DateTimeField()),
                ('created_date_bs', models.CharField(max_length=10)),
                ('name', models.CharField(help_text='Discount scheme name must be max 50 characters', max_length=50, unique=True)),
                ('editable', models.BooleanField(default=False)),
                ('rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Discount Rate default=0.00 max upto 100.00', max_digits=5)),
                ('active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BankDeposit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date_ad', models.DateTimeField()),
                ('created_date_bs', models.CharField(max_length=10)),
                ('deposit_date_ad', models.DateTimeField()),
                ('deposit_date_bs', models.CharField(blank=True, max_length=10)),
                ('deposit_by', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, help_text='User can input value upto 99999999.99', max_digits=12)),
                ('remarks', models.CharField(max_length=50)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_app.bank')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AppAccessLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date_ad', models.DateTimeField()),
                ('created_date_bs', models.CharField(max_length=10)),
                ('device_type', models.PositiveBigIntegerField(choices=[(1, 'Mobile'), (2, 'PC'), (3, 'Tablet'), (4, 'Other')], default='NA', help_text='where 1=Mobile, 2=PC, 3=Tablet and 4=Other')),
                ('app_type', models.PositiveBigIntegerField(choices=[(1, 'Web-App'), (2, 'IOS-App'), (3, 'Android-App')], default='NA', help_text='where 1=Web-App, 2=IOS-APP, 3=Android-APP')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AdditionalChargeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date_ad', models.DateTimeField()),
                ('created_date_bs', models.CharField(max_length=10)),
                ('name', models.CharField(help_text='Additional Charge type name must be max 50 characters', max_length=50, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
