# Generated by Django 3.1.9 on 2021-08-02 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
        ('sale', '0002_auto_20210727_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saledetail',
            name='ref_purchase_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_details', to='purchase.purchasedetail'),
        ),
    ]
