# Generated by Django 3.1.9 on 2021-07-12 05:33

from django.db import migrations, models
import tenant.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('schema_name', models.CharField(max_length=100, unique=True, validators=[tenant.models.validate_schema_name])),
                ('sub_domain', models.CharField(max_length=300, unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
