# Generated by Django 3.1.9 on 2021-07-12 05:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date_ad', models.DateTimeField()),
                ('created_date_bs', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=20, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date_ad', models.DateTimeField()),
                ('created_date_bs', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=20)),
                ('capacity', models.IntegerField()),
                ('no_of_attendant', models.IntegerField(blank=True, default=0)),
                ('status', models.PositiveIntegerField(choices=[(1, 'OCCUPIED'), (2, 'VACANT'), (3, 'RESERVED')], default=2, help_text='Where 1= OCCUPIED, 2 = VACANT, 3 = RESERVED')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('block', models.ForeignKey(help_text='ForeignKey', on_delete=django.db.models.deletion.CASCADE, to='rims_setup.block')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='customer.customer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
