# Generated by Django 3.1.9 on 2021-07-12 05:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sale', '0001_initial'),
        ('core_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer_order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvanceDeposit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date_ad', models.DateTimeField()),
                ('created_date_bs', models.CharField(max_length=10)),
                ('advance_deposit_type', models.PositiveIntegerField(choices=[(1, 'DEPOSIT'), (2, 'DEPOSIT-RETURN')], help_text='Advance Deposit type like 1= Deposit, 2 = Return')),
                ('deposit_no', models.CharField(help_text='max deposit_no should not be greater than 13', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Maximum value upto 99999999999.99', max_digits=12)),
                ('remarks', models.CharField(blank=True, max_length=50)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('order_main', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='advance_deposits', to='customer_order.ordermain')),
                ('sale_main', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sale_main', to='sale.salemain')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AdvanceDepositPaymentDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date_ad', models.DateTimeField()),
                ('created_date_bs', models.CharField(max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Maximum value upto 99999999999.99', max_digits=12)),
                ('remarks', models.CharField(blank=True, help_text='remarks can be upto 50 characters', max_length=50)),
                ('advance_deposit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='advance_deposit_payment_details', to='advance_deposit.advancedeposit')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('payment_mode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core_app.paymentmode')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
