# Generated by Django 3.1.9 on 2021-07-12 05:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import src.user_group.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPermissionCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name can have max of 50 characters', max_length=50)),
                ('created_date_ad', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_date_bs', models.CharField(max_length=10)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name can have max of 50 characters', max_length=50)),
                ('code_name', models.CharField(help_text='Code Name can have max of 50 characters', max_length=50, validators=[src.user_group.models.validate_code_name])),
                ('created_date_ad', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_date_bs', models.CharField(max_length=10)),
                ('category', models.ForeignKey(blank=True, help_text='foreign key to UserPermissionCategory', null=True, on_delete=django.db.models.deletion.PROTECT, to='user_group.userpermissioncategory')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name can have max of 50 characters', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='default value is True')),
                ('created_date_ad', models.DateTimeField()),
                ('created_date_bs', models.CharField(max_length=10)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('permissions', models.ManyToManyField(blank=True, help_text='Many to many connection with Permissions', to='user_group.UserPermission')),
            ],
        ),
    ]
